testbed:
    name: testbed-AG9-9
    alias: tb-AG9-9
    type: Physical # Physical or Virtual
#    credentials:
#        username: admin
#        password: broadcom

devices:

    AG9032v1-54:
        deviceType: IOS
        deviceType: ICOS
        alias: rtr1
        management_ip : 10.62.2.54
        connections:
              protocol: telnet
              ip: 10.62.2.251
              port: 1054
        credentials:
            username: admin
            password: broadcom
            enable_password: broadcom

    AG9032v1-36:
        deviceType: ICOS
        alias: rtr2
        management_ip : 10.62.2.36
        connections :
              protocol: telnet
              ip: 10.62.2.251
              port: 1036
        credentials:
            username: admin
            password: broadcom
            enable_password: broadcom

# Topology is optional. It is not necessary unless you want to use topology features in testbed.
topology:
    AG9032v1-54:
        interfaces:
            0/1:
                alias: rtr1-intf0
                link: rtr1-rtr2-1
                type: ethernet
                ipv4: 1.1.1.1/24
    AG9032v1-36:
        interfaces:
            0/5:
                alias: rtr2-intf0
                link: rtr1-rtr2-1
                type: ethernet
                ipv4: 1.1.1.2/24

